GET http://localhost:5000/mangas

###
GET http://localhost:5000/mangas/claymore

###
GET http://localhost:5000/mangaclash/hot

###
GET http://localhost:5000/mangas/claymore/chapters/1/images/

###
GET http://localhost:5000/mangaclash/manga/Martial%20Peak?link=https%3A%2F%2Fmangaclash.com%2Fmanga%2Fmartial-peak%2F